### ISSUE TITLE
Not working on Android Studio 3.6 Canary 1 with multiple devices connected

### ISSUE THREAD

**Issue by Stonos** [pbreault/adb-idea#110]
Getting the following exception when trying to use ADB Idea with multiple devices connected (it works fine when there is only one device connected):
```
java.lang.NoSuchMethodError: com.android.tools.idea.model.AndroidModuleInfo.getRuntimeMinSdkVersion()Lcom/android/sdklib/AndroidVersion;
	at com.developerphil.adbidea.ui.MyDeviceChooser.<init>(MyDeviceChooser.java:115)
	at com.developerphil.adbidea.ui.DeviceChooserDialog.<init>(DeviceChooserDialog.java:40)
	at com.developerphil.adbidea.adb.DeviceResultFetcher.showDeviceChooserDialog(DeviceResultFetcher.kt:72)
	at com.developerphil.adbidea.adb.DeviceResultFetcher.fetch(DeviceResultFetcher.kt:37)
	at com.developerphil.adbidea.adb.AdbFacade.executeOnDevice(AdbFacade.java:73)
	at com.developerphil.adbidea.adb.AdbFacade.clearData(AdbFacade.java:57)
	at com.developerphil.adbidea.action.ClearDataAction.actionPerformed(ClearDataAction.java:10)
	at com.developerphil.adbidea.action.AdbAction.actionPerformed(AdbAction.java:13)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:261)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:278)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$7(GotoActionAction.java:351)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionLater$4(TransactionGuardImpl.java:271)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:729)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:678)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by Dreyar** [comment]
I can confirm that and on Studio 3.6 Canary 3

**Comment by kikasik** [comment]
Same on Android Studio 3.6 Canary 11

**Comment by pbreault** [comment]
Thanks for the report. This is fixed in 1.5.4
